#!/bin/bash

yadm stash
yadm submodule update --init --recursive
yadm alt

. ~/.local/shell/99-src.sh

colorText 4 "Checking topgrade..."
if ! command -v topgrade
then
  curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo topgrade-rs/topgrade --to ~/.local/bin -f
fi

colorText 4 "Checking sheldon..."
if ! command -v sheldon
then
  curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin -f && ~/.local/bin/sheldon lock --update
fi

colorText 4 "Resetting ssh perms..."
chmod -R a-xst+X,u+rw,go-rwx ~/.ssh/
