#!/bin/bash

. ~/.local/shell/99-src.sh

colorText 4 "Checking for sheldon plugin updates..."
cmd sheldon && sheldon lock --update

colorText 4 "Checking dangling symlinks in $HOME/.config..."
cmd symlinks && symlinks -rd ~/.config/ 2>&1 | sed -e '/absolute/d' -e '/other_fs/d' -e '/messy/d'

colorText 4 "Resetting ssh perms..."
chmod -R a-xst+X,u+rw,go-rwx ~/.ssh/
